version: '3.5'

services:
  redis:
    restart: unless-stopped
    image: redis
    ports:
      - "127.0.0.1:6379:6379"

#  telegram-search:
#    build: .
#    restart: unless-stopped
#    depends_on:
#      - redis
#      - elasticsearch
#    volumes:
#      - ./session:/app/session
#    environment:
#      - REDIS_HOST=redis
#      - ELASTIC_URL=http
#      - API_ID=1354710
#      - API_HASH=
#      - BOT_TOKEN=1

  elasticsearch:
    build: ./elasticsearch
    restart: unless-stopped
    volumes:
      - /Users/xie/telegram-search/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9200"

volumes:
  data:
